## General Settings
name: Jonathan's Test Site
description: Trying out GH Pages
url: "http://jtmullen.github.io"
theme: jekyll-theme-minimal
markdown: GFM

github_username: jtmullen

social_links:
  github:  jtmullen
  linkedIn: in/JTM 