## General Settings
title: Jonathan Mullen
author: jtmullen
copyright: Copyright © 2020-2021
name: Jonathan Mullen
description: My Personal Site

baseurl: ""
url: "http://jtmullen.github.io"
favicon: "/img/favicon.ico"

remote_theme: "jtmullen/jekyll-theme-yat"
show_downloads: false
markdown: GFM

header_pages:
  - index.html
  - about.md

github_username: jtmullen

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-remote-theme